### ISSUE TITLE
Name plugins

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#107]
The plugins should have the following names and types when registered:

```
GENE_LIST = "GeneList"
RNA_SEQ = "RNASeq"
BIOM = "BIOM"
ISA = "ISA"
BIGWIG = "BigWig"
```

## EDIT:

1. The above list may not be correct, Steve will provide a correct list below.
2. In addition to renaming the plugins, there will need to be a new env var added per plugin for the display name of the plugin.  This will need to be returned as part of the dataset type object.

## Steps

* [x] Add the new environment variable to the commons library
* [x] PR the change to the commons library
* [x] Tag the new version of the commons library
* [x] Publish the new version of the commons library
* [x] Update the plugin service to use the new version of the commons library
* [x] PR the change to the plugin service
* [x] Tag the updated plugin service
* [x] Wait for jenkins to build the new plugin service tag
* [x] Update the plugin base image to use the new plugin service tag
* [x] Tag the plugin base image
* [x] Wait for jenkins to build the new plugin base image
* [x] Update the bigwig plugin to use the new plugin base image
* [x] Update the genelist plugin to use the new plugin base image
* [x] Update the rnaseq plugin to use the new plugin base image
* [x] Update the isa plugin to use the new plugin base image
* [x] Update the biom plugin to use the new plugin base image
* [x] update the vdi service to use the new commons version
* [x] Update the vdi service to require the new environment variable
* [x] Add the new environment variable to the .env files
* [x] Add the display name field to the raml for the dataset info responses
* [ ] Weave the new display name field into the process to return it as part of the dataset info responses

**Comment by Foxcapades** [comment]
@steve-fischer-200 Please provide a mapping of correct plugin names to display names.

**Comment by steve-fischer-200** [comment]
NAME   DISPLAY_NAME
BigwigFiles Bigwig
GeneList Gene list
RnaSeq RNA-seq
ISA   ISA Study
BIOM BIOM
