### ISSUE TITLE
Admin endpoint to retry dataset soft-delete/uninstall.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#204]
As there are a number of reasons a dataset may not have been uninstalled by VDI's automated processes, there should be an endpoint that triggers a soft-delete event which will cause VDI to reattempt dataset uninstallation in all of the dataset's install targets.

**Comment by steve-fischer-200** [comment]
I dont really understand this.   If the dataset already has soft-delete set, why would a soft-delete event trigger an uninstall?

**Comment by Foxcapades** [comment]
The original reasoning for this ticket has been lost to time.  If we remember what this was about or run an issue relating to this in the future we can open a new ticket.
