### ISSUE TITLE
Update VDI dataset details endpoints to retrieve account info from bearer token instead of directly from account DB

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/vdi-service#325]
## Overview
* Update the usages of https://github.com/VEuPathDB/vdi-service/blob/main/service/rest-service/src/main/kotlin/org/veupathdb/service/vdi/db/AccountDB.kt to use new container core functions to get account details
* The static methods of this class can be used in their stead: https://github.com/VEuPathDB/lib-jaxrs-container-core/blob/master/src/main/java/org/veupathdb/lib/container/jaxrs/providers/UserProvider.java#L49C26-L55

## Cleanup
* The AccountDB connection details can be cleaned up from the environment after this

**Comment by Foxcapades** [comment]
Completed by @steve-fischer-200 in #330
