### ISSUE TITLE
Add a mechanism for galaxy to import on behalf of users

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/vdi-service#70]
## Overview
Currently, Galaxy has a "super-user" that is used to import on behalf of users. We'll need an analogy for VDI to enable imports from Galaxy to VDI.

**Comment by Foxcapades** [comment]
Due to the way our authentication and user-to-dataset linking works now this may need to be a separate endpoint.  That or we will need to manually replicate or use a custom auth filter to authenticate the super user on behalf of the target user.

**Comment by Foxcapades** [comment]
Plan:

* New endpoint that will:
    * accept as an Auth-Key header value the admin secret key
    * accept as a User-ID header value the ID of the target user on whose behalf we are importing the dataset
    
This endpoint will need to validate the user ID and look up the user in the account database (via FgpUtil?) to pass to the service.

**Comment by Foxcapades** [comment]
Blocked by #74
